#pragma once

#include <cstdint>

#include "libreshockwave/player/web/WasmRuntime.hpp"

#if defined(__EMSCRIPTEN__)
#include <emscripten/emscripten.h>
#define LIBRESHOCKWAVE_WASM_EXPORT extern "C" EMSCRIPTEN_KEEPALIVE
#else
#define LIBRESHOCKWAVE_WASM_EXPORT extern "C"
#endif

namespace libreshockwave::player::web {

[[nodiscard]] WasmRuntime& wasmExportRuntime();

} // namespace libreshockwave::player::web

LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_allocate_buffer(int size);
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_string_buffer_address();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_string_buffer_capacity();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_load_movie(int movieSize, int basePathLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_initial_builtin_symbol(int keyLen, int valueLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_movie_property(int keyLen, int valueLen);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_read_next_goto_net_page();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_read_next_goto_net_movie();

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_preload_casts();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_play();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_tick();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_pause();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_stop();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_go_to_frame(int frame);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_step_forward();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_step_backward();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_script_timeout_ms(int milliseconds);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_script_timeout_ms();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_debug_playback_enabled(int enabled);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_add_trace_handler(int nameLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_remove_trace_handler(int nameLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_clear_trace_handlers();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_current_frame();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_frame_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_tempo();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_puppet_tempo(int tempo);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_stage_width();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_stage_height();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_render();
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_render_buffer_address();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_sprite_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_type();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_update_cursor_bitmap();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_bitmap_width();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_bitmap_height();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_bitmap_length();
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_cursor_bitmap_address();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_reg_point_x();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_cursor_reg_point_y();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_is_caret_visible();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_caret_x();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_caret_y();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_caret_height();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selection_rect_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selection_rect_x(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selection_rect_y(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selection_rect_w(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selection_rect_h(int index);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_paste_text(int textLen);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_selected_text_length();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_cut_selected_text();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_select_all();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_debug_log();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_call_stack();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_window_sprite_diagnostics();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_visible_text_diagnostics();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_bootstrap_diagnostics();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_script_diagnostics();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_net_debug_status();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_done();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_error();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_task_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_last_task_id();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_pending_request_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_pending_movie_navigation_task_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_net_latest_task_done();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_trigger_test_error();

LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_set_external_param(int keyLen, int valueLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_clear_external_params();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mouse_move(int stageX, int stageY);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mouse_down(int stageX, int stageY, int button);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mouse_up(int stageX, int stageY, int button);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_blur();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_key_down(int browserKeyCode, int keyCharLen, int modifiers);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_key_up(int browserKeyCode, int keyCharLen, int modifiers);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_task_id(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_url(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_method(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_post_data(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_fallback_count(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_fetch_fallback_url(int index, int fallbackIndex);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_drain_pending_fetches();
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_allocate_net_buffer(int size);
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_net_buffer_address();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_deliver_fetch_result(int taskId, int dataSize);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_deliver_fetch_status(int taskId, int byteCount);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_deliver_fetch_error(int taskId, int status);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_jpeg_decode_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_jpeg_decode_id(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_pending_jpeg_decode_data(int id);
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_pending_jpeg_decode_data_address();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_deliver_jpeg_decode_result(
    int id, int width, int height, int dataLen);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_action(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_channel(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_format(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_loop_count(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_volume(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_audio_pending_data(int index);
LIBRESHOCKWAVE_WASM_EXPORT std::uintptr_t libreshockwave_wasm_get_audio_buffer_address();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_drain_audio_pending();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_audio_notify_stopped(int channelNum);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_count();
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_type(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_instance_id(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_host(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_port(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_mus_pending_send_data(int index);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_drain_mus_pending();
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mus_deliver_connected(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mus_deliver_disconnected(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mus_deliver_error(int instanceId, int errorCode);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_mus_deliver_message(int instanceId, int dataLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_mus_request_connect(
    int instanceId, int hostLen, int port, int mode);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_mus_request_send_text(
    int instanceId, int senderLen, int subjectLen, int contentLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_mus_request_disconnect(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_is_connected(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_mus_destroy_instance(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_poll_message_count(int instanceId);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_message_error(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_message_sender(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_message_subject(int index);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_mus_message_content(int index);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_set_global_string(int keyLen, int valueLen);
LIBRESHOCKWAVE_WASM_EXPORT void libreshockwave_wasm_debug_set_global_int(int keyLen, int value);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_call_handler(int nameLen);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_call_handler_string_arg(int nameLen, int argLen);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_get_global_string(int keyLen);
LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_debug_get_global_int(int keyLen);

LIBRESHOCKWAVE_WASM_EXPORT int libreshockwave_wasm_get_last_error();

#undef LIBRESHOCKWAVE_WASM_EXPORT
